name: Android CI

on:
  workflow_dispatch:
  # push:
  #   branches: ['feature/pipeLine']
  # pull_request:
  #   branches: ['mainLocal']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Run Yarn Install
        run: |
          yarn install

      - name: Build application
        run: |
          cd android
          ./gradlew assembleRelease

      - name: List contents of the android/app directory
        run: |
          echo "Listing contents of the android/app directory:"
          ls -R ./android/app

      - name: Check if build directory exists inside android/app
        run: |
          if [ -d ./android/app/build ]; then
            echo "Build directory exists inside android/app. Listing contents:"
            ls -R ./android/app/build
          else
            echo "Build directory does NOT exist inside android/app."
            exit 1
          fi
      - name: Get latest commit
        id: vars
        run: echo ::set-output name=LATEST_COMMIT_MESSAGE::$(echo $(git log -1 --pretty=format:"%s"))

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: Developer
          file: './android/app/build/outputs/apk/release/app-release.apk'
          releaseNotes: ${{ steps.vars.outputs.LATEST_COMMIT_MESSAGE }}
