name: Distribute App via Firebase

on:
  workflow_dispatch:

jobs:
  firebase_distribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List contents of the android/app directory
        run: |
          echo "Listing contents of the android/app directory:"
          ls -R ./android/app

      - name: Check if build directory exists inside android/app
        run: |
          if [ -d ./android/app/build ]; then
            echo "Build directory exists inside android/app. Listing contents:"
            ls -R ./android/app/build
          else
            echo "Build directory does NOT exist inside android/app."
            exit 1
          fi

      - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: Developer
        file: './android/app/build/outputs/apk/release/app-release.apk'
       
